apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
spec:
  interval: "${infrastructure_eso_release_interval:=30m}"
  chart:
    spec:
      chart: external-secrets
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets-operator
      interval: 12h
